### 常量的学习
* numpy.nan 表示空值 nan =NaN=NAN

In [2]:
import numpy as np
print(np.nan == np.nan) # False

x = np.array([1,1,3,np.nan]) # 创建一个一维数组，其中有元素为空值
print(x) #[1. 1. 3. nan ]
y = np.isnan(x) #逐个判断数组中的元素是否为空  [False False False True]
print(y)
z = np.count_nonzero(y) #统计数组中非0元素的个数
print(z) # 1

False
[ 1.  1.  3. nan]
[False False False  True]
1


### 数据类型
为了方便科学计算，numpy中会定义一些数据类型如numpy.float32,numpy.int32等；具体可以官网参考
* dtype:numpy中数值类型实际为dtype实列
* 通过numpy.dtype可以获取数据中元素的数值类型

In [9]:
x = np.arange(0,6,1).reshape(2,3)
print(x.dtype)
y = np.arange(0,6,1,dtype=np.int32)
print(y.dtype)

int32
int32


### 时间日期和时间增量
* datetime64 和 timedelta64 运算 
* 日期相关的计算
* datetime64 字符串转日期等
* timedelta64 时间计算

In [10]:
begindates = np.datetime64('2020-07-10')
enddates = np.datetime64('2020-07-20')
a = np.busday_count(begindates, enddates)
b = np.busday_count(enddates, begindates)
print(a)
print(b)

6
-6


### 数组的创建
* numpy.array与asarray 一般可以通过python中的数组，列表等，通过numpy.array初始化
    * 一般array会新创建一个ndarray，将数据拷贝到新的ndarray中，而当asarray接收的ndarray时,且不修改原来的数据类型时，不会创建新的，所以原来的值修改‘
    会导致随之修改
* numpy.zeros,numpy.ones,numpy.emptys
* numpy.arange(start,end,step)
* numpy.linspace()
* fromfunction:一般在绘制图像时会用到


In [60]:
#通过np.arrray
a = np.array([1,2,3,4,5,7]) # 列表
b = np.array((1,2,3,4,5,7)) #元组
print(a,type(a))
print(b,type(b))

print(a.reshape(2,3))#通过reshape，转成二维数组
print(a.reshape(2,1,3)) ##通过reshape，2个1*3的

#np.asarray，及与array区别
x = np.array([[1,2,3],[4,5,6]])
y = np.array(x)
z = np.asarray(x)
w = np.asarray(x,dtype=np.float)
x[1][1]=0
print(x,type(x),x.dtype)
print(y,type(y),y.dtype)
print(z,type(z),z.dtype)#与x公有一个数据，指向同一份数据
print(w,type(w),w.dtype) #w修改了原来x数据类型，所以重新创建一个ndarray,所以当x变化时，w不会随之改变


# fromfunction函数，可以从函数中创建数组;在每个坐标轴上执行定义的函数
# 在原始矩阵中，根据元素的（x,y）索引带入计算  比如（2，2）的矩阵
def f(x,y):
    return x*1+y 
x = np.fromfunction(f,(2,2),dtype=int) # (2,2)即数组shape 2*2的矩阵
print(x)

# ones,zeros,zeor_like一般在机器学习中初始化时，通常初始化为0，可以创建一个固定大小的初始矩阵
# 同理ones和ones_like与zeros相同，只不过是创建全为1的ndarray
# 而empty和empty_like则是创建一个随机的数组
x1 = np.zeros((5,)) # (x,y)表示数组的shape
x2 = np.zeros(5) # 创建一维数组时也可以这样
x3 = np.zeros((3,4))
x4 = np.zeros((2,4,4))
print(x1)
print(x2)
print(x3)
print(x4)
#zero_like,创建一个与数组a相同shape的ndarray
x5 = np.zeros_like(x2)
print(x5)

#empty
y1= np.empty((6,4))
print(type(y1),y1)


# eye，对角线上为1，其他为0的数组
#identity 返回一个对角线上为1的方阵
#diag对角矩阵
# full,full_lilke 常数数组，指定矩阵中元素的常数值
z1 = np.eye(2,3)
print(z1)
x1 = np.full(2,7)
x2 = np.full((2,3),7) #(2,3) shape  7:填充的值
print(x1)
print(x2)


#arange(start,stop,step) a1=start a2=start + step ...an<stop-step  等差数列：an=a1 +(n-1)*d  所以n<=（stop-start）/d + 1
#linspace(start,stop,num)返回start,stop中一定数量（num） 比如start=1 stop=5 num=10 则（5-1）/(10-1)
#logspace(start,stop,num) 以对数刻度均匀分布
#random.rand(d1,d2,d3)表示坐标轴，如(2,3)表示2行三列
x1 = np.linspace(1,5,10)
x2 = np.arange(1,5,3)
x3 = np.logspace(0,1,3)
x4 = np.random.rand(2,3,2)
print(x1)
print(x2)
print(x3)
print(x4)

[1 2 3 4 5 7] <class 'numpy.ndarray'>
[1 2 3 4 5 7] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 7]]
[[[1 2 3]]

 [[4 5 7]]]
[[1 2 3]
 [4 0 6]] <class 'numpy.ndarray'> int32
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> int32
[[1 2 3]
 [4 0 6]] <class 'numpy.ndarray'> int32
[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float64
[[0 1]
 [1 2]]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'> [[1.25272826e-311 7.55920438e-322 0.00000000e+000 0.00000000e+000]
 [1.69119330e-306 1.16096346e-028 1.04857803e-142 1.16467185e-028]
 [1.42646471e-153 4.43550427e-019 4.17985905e+222 1.43616552e+161]
 [4.08361127e+223 1.29038135e-057 1.06148061e+170 4.52745891e+257]
 [9.27777192e+242 2.69373275e+132 8.48939199e+136 3.63385226e-043]
 [6.19337450e-071 4.10123869e+223 8.45915361e-053 7.78045999e-143]]
[[1. 0

### 结构数组的创建
* 类似sql数据中字段，以及excel中的列名
* 字典定义数组结构 
* 多个元组列表定义结构
* 一般机器学习中每个特征都有对应的特征名称

### 数组的属性
* dtype：表示数组对象的元素类型，即数组中元素的类型
* ndim:数组的维数（即轴的个数）如一维数组是1，二维数组是2，三维数组是3
* shape:返回一个元组，表示数组的形状如（2，3）表示一个二维矩阵，2行3列  （2，2，3）则表示2个2*3的矩阵
* size：数组中元素的总数如shape=（2，3）,则size=2*3=6 (2,2,3)则size=2*2*3=12
* itemsize，以字节的形式返回数组中每一个元素的大小


In [70]:
print(a.size,a.itemsize,x4.itemsize)

2 136 8
