*  对于一个多维数组，我们会需要获取数组中某些区域的元素，或某个指定位置的元素，那么这时需要通过索引进行定位
	* 一般通过shape思路，通过坐标轴进行定位，如对于二维数组(3,8)中，对元素进行定位索引从0开始 [1,2]即取第一行第二列那个元素
	* 当取区域时，则划定行范围和列范围，符号“:”表示剩下元素 2：则表示取3行或3列开始往后的   2：4则指定了范围

* 数组的拷贝
	* 浅拷贝：引用，指向同一份数据，内存地址相同，当一个改变时，另外一个也会发生改变
	* 深拷贝：copy创建一份新的数据，与老的没有关系
 

#### 视图与副本
* 视图：即浅拷贝，指向的还是同一份数据，指向同一个内存地址
* 副本：copy

In [2]:
import numpy as np
x = np.array((1,2,3,4,5,6))
print('before',x)
y = x # 返回一个数据的视图，即当x发生改变时，y也会发生改变
z = x.copy() # 创建一个新的数组，拷贝到数组中，x和z指向不同的数据，当x发生改变时，对z没有改变
y[0]=-1

print(x)#发生改变
print(y)#发生改变
print(z)#可以发现z没有发生改变

before [1 2 3 4 5 6]
[-1  2  3  4  5  6]
[-1  2  3  4  5  6]
[1 2 3 4 5 6]


#### 切片与索引
* 切片只是返回原数组的视图，通过索引方式返回数组的部分
* 索引：通过圈定坐标轴的范围，返回指定范围的元素
    * 索引方式：([x,y,z]) x可以指定行范围，y,z类似
    * x：start:stop:step 不包含stop
    * 数组索引:传入索引值

In [24]:
x = np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
print(type(x),x.dtype,x.shape,x)

y1 = x[2:,3] # 从第三行开始，取第4列的值，最后返回[13]
y2 = x[1:,2:] # 从第2行开始，取第4列的值，最后返回[9,13]
y3 = x[1:,]
y4 = x[1:] # 后面的y轴可以省略
y5 = x[1:2,0:5]
y6 = x[1:2,0:3:2] # step=2
y7 = x[1:2,0::2] # 没有设置stop值
index = [[1,0,2]] #对应的行号
y8 = x[index] # 数组索引
print(y1)
print(y2)
print(y3)
print(y4)
print('y5',y5)
print('y6',y6)
print('y7',y7)
print('y8',y8)

<class 'numpy.ndarray'> int32 (3, 4) [[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]
[13]
[[ 8  9]
 [12 13]]
[[ 6  7  8  9]
 [10 11 12 13]]
[[ 6  7  8  9]
 [10 11 12 13]]
y5 [[6 7 8 9]]
y6 [[6 8]]
y7 [[6 8]]
y8 [[ 6  7  8  9]
 [ 1  2  3  4]
 [10 11 12 13]]


d:\program files\python36\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  if sys.path[0] == '':
