### 数组操作
* 由于一般在操作过程中，比如初始化创建数组时，可以先创建一个1维数组，通过reshape方式改变形状转成二维数组

#### 更改数组形状
* reshape(x,y,z...)表示各轴的大小,返回的时原来数组的一个视图，修改后会关联发生改变
    * newshape=[rows，-1]，根据rows自动推断，列是多少，不用自己写清楚
* arra.shape = [x,y,z]
* numpy.ndarray.flat 将数组打平，转成一维数组，一般可以调用此方法，遍历数组中的每个元素
* flatten 返回的是一个副本，所以不是指向同一个内存地址的数据


In [19]:
import numpy as np
x = np.random.randint(1,10,10)
print(x)
print('x',type(x),x.ndim,x.shape,x)
x2 = x.reshape(2,5) # 返回一个5*2的数组，x的视图
x3 = x.reshape(2,-1) # 参数为-1时，会根据行数，自动推断列数，size=rows*cols
x2[0]=-1 # x2发生改变，则x也会发生改变

x.shape = [5,2] # x shape
print('x.shape',x)
print(x2)
print('x2',x2,'x3',x3,'x',x)

# flatten 返回副本，指向不同地址，所以改变，原来不会发生改变
x3 = x.flatten()
print('x3',x3)
x3[0]= 0
print('x3 af',x3,'ori x',x)

[3 1 6 4 7 7 9 2 9 1]
x <class 'numpy.ndarray'> 1 (10,) [3 1 6 4 7 7 9 2 9 1]
x.shape [[-1 -1]
 [-1 -1]
 [-1  7]
 [ 9  2]
 [ 9  1]]
[[-1 -1 -1 -1 -1]
 [ 7  9  2  9  1]]
x2 [[-1 -1 -1 -1 -1]
 [ 7  9  2  9  1]] x3 [[-1 -1 -1 -1 -1]
 [ 7  9  2  9  1]] x [[-1 -1]
 [-1 -1]
 [-1  7]
 [ 9  2]
 [ 9  1]]
x3 [-1 -1 -1 -1 -1  7  9  2  9  1]
x3 af [ 0 -1 -1 -1 -1  7  9  2  9  1] ori x [[-1 -1]
 [-1 -1]
 [-1  7]
 [ 9  2]
 [ 9  1]]


#### 数组转置
* transpose(arra)
* arra.T
* 两者基本没有区别，但是当数组维度<2时，transpose有返回

In [27]:
x = np.arange(0,10,1)
print(x)
print('x.T',x.T)
x1 = np.transpose(x)
print(' np.transpose(x)',x1)

x3 = x.reshape(2,5)
print('x.reshape(2,5)',x3)
print('x3.T',x3.T)
x4 = np.transpose(x3)
print(' np.transpose(x3)',x4)

[0 1 2 3 4 5 6 7 8 9]
x.T [0 1 2 3 4 5 6 7 8 9]
 np.transpose(x) [0 1 2 3 4 5 6 7 8 9]
x.reshape(2,5) [[0 1 2 3 4]
 [5 6 7 8 9]]
x3.T [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
 np.transpose(x3) [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


#### 更改维度
* 当需要修改数组维度时，如新增维度或者减少维度
* numpy.newaxis
* numpy.squeeze(arra,axis)：删除单维度
    * arra：表示输入数组
    * axis 用于指定需要删除的维度，必须是指定的单维度,即指定维度大小为1
    * 在机器学习和深度学习中，通常算法的结果是可以表示向量的数组（即包含两对或以上的方括号形式[[]]），如果直接利用这个数组进行画图可能显示界面为空（见后面的示例）。我们可以利用squeeze()函数将表示向量的数组转换为秩为1的数组，这样利用 matplotlib 库函数画图时，就可以正常的显示结果了。
    

In [45]:
x = np.arange(0,12,1)
x1 = x.reshape(2,1,-1)
print('x1',x1)
x2 = x1[np.newaxis] # shape:(1, 2, 5)增加了一个维度
print(x2,x2.shape)
x3 = np.squeeze(x2,0)
x4 = np.squeeze(x1,1) # error cannot select an axis to squeeze out which has size not equal to one
print('x3',x3)
print('x4',x4)

x1 [[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]]
[[[[ 0  1  2  3  4  5]]

  [[ 6  7  8  9 10 11]]]] (1, 2, 1, 6)
x3 [[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]]
x4 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### 数组组合
* 将两个数组拼接到一起
* 按照一定的方式，将数组拼接；最直接的方法，是沿着坐标轴将两个数组拼接，这时在该轴上，两个数组大小一样，比如按照行拼接，则行数一样
* np.concatenate((a1,a2,a3...),axis=0,out=None) 拼接后，创建一个新的ndarray，和原来不指向同一个内存地址
    * axis=0 默认是行拼接,axis不能大于原来数组的维度
    * out:ndarray，用来将返回的结果放入out中，与返回新的ndarray指向同一内存地址

In [56]:
x1 = np.array([1,2,3])
x2 = np.array((4,5,6))
x4 = np.zeros(6)
x3 = np.concatenate([x1,x2],out=x4) # ([x1,x2])或((x1,x2))都可以
x3[0]=-2
print('x1',x1,'x2',x2,'x3',x3)
print(x4)

x5 =np.concatenate([x1.T,x2.T],axis=1, out=x4)
print(x5)

x1 [1 2 3] x2 [4 5 6] x3 [-2.  2.  3.  4.  5.  6.]
[-2.  2.  3.  4.  5.  6.]


AxisError: axis 1 is out of bounds for array of dimension 1